### ISSUE TITLE
Support for RxJava 2

### ISSUE THREAD

**Issue by alexodus** [mcharmas/Android-ReactiveLocation#132]
it would be great!:)

**Comment by patloew** [comment]
Since RxJava progressed pretty much since this library was created (for example, `Observable.create()` should not be used anymore in RxJava 1), I decided to do a complete rewrite of the functionality provided by this library, for RxJava 2. An additional reason for a separate library was that I've integrated the possibility to handle location settings resolution directly in the library (which I also wanted to add here in Pull Request #93, but it was not merged unfortunately). So, you might want to take a look at the new library I made: [RxLocation](https://github.com/patloew/RxLocation).

**Comment by elirangoshen** [comment]
I made pull request after i migrate it to rxjava2.
waiting for an answer :)

**Comment by mcharmas** [comment]
Support for RxJava added in v2.0. Propagating to maven central.
