### ISSUE TITLE
Activity Recognition

### ISSUE THREAD

**Issue by cyrixmorten** [mcharmas/Android-ReactiveLocation#21]
I have created this fork adding support for activity recognition: https://github.com/cyrixmorten/Android-ReactiveLocation

The sample has also been updated to demonstrate the new feature. For this, I have had to add a Start/Stop button, allowing the Activity detection to continue running after onStop. All subscriptions are always unsubscribed  in onDestroy, though. 

Before requesting a merge, I have a problem that I would like to find a solution to. The usage of Activity Recognition requires the DetectedActivity results be handed to an IntentService. This pattern does seemingly not fit well with RxJava, as I would like to feed the results to an observer living outside the IntentService.

My initial attempt was based on passing a ResultReceiver to the intent that is handed to the IntentService by a PendingIntent. This idea is based on the answers to this SO question: http://stackoverflow.com/questions/4510974/using-resultreceiver-in-android 
The relevant code is kept but commented out in ActivityUpdatesObservable

Unfortunately it turns out that passing any values to the intent this way makes it 'freeze' in the current state. That is, the values are not updated properly to reflect the detected activity, rather, the passed information is just repeated. 

I hope that you, or someone else reading this has more knowledge on the subject and can come up with a way around the problem.
Also added a question on SO on the subject: http://stackoverflow.com/questions/27757437/activityrecognitionresult-hasresultintent-false-when-adding-extras-to-the-inte

Currently, I have simply created a static reference to the observer that the IntentService can grab, calling onNext with the detected activity. This is not an acceptable solution as it allows only one observer at a time. Nonetheless, it is working and is a start.

**Comment by mcharmas** [comment]
My first idea on this subject would be to use BroadcastReceiver instead of IntentService. You can register ad-hoc broadcast receiver and create for it proper PendingIntent.

So the way subscription should work would be:
- register receiver using context
- register for activity recognition updates passing pending intent to receiver created in previous point

That way when activity change is available receiver would be notified and we could pass the data through observable stream.

Unregistering would be analogus:
- unregistering from gcm
- unregistering previously registered broadcast receiver

I think that it is not doable with IntentService. What do you think about it @cyrixmorten ?

**Comment by cyrixmorten** [comment]
Thank you for the feedback

Sounds like a good idea indeed. Will try it out as soon as I have some time on my hands. 

I suspect I might have to do some form of threading, thinking that the sample from Google must have a reason for using an IntentService. Might be too expensive operations for the main thread to handle, though on the other hand the IntentService only pick the handed DetectedActivity with most confidence from a set of options.

I don't know. Might be easier to determine when testing the solution.

**Comment by mcharmas** [comment]
Strange - it doesn't look that it does any heavy work - data is in the Intent and all the sample does is unpacking. My guess is they did it in IntentService to demonstrate PendingIntent usage and now all the world is using it wrong... I hope I am wrong. In any case threading should not be a problem because that's what RxJava is doing best:-) Please let me know when you take a closer look into this.

**Comment by cyrixmorten** [comment]
Think I made it work, will do some further testing before a merge.

What I ended up doing was using IntentService, as the sample, then re-broadcast the received intent. 

For whatever reason, it did not work using Broadcasts directly. One of the guys from my university was pretty certain that it had to go through an IntentService as well. 

Just wanted to give an update.

**Comment by mcharmas** [comment]
Done and working in v0.4.
