### ISSUE TITLE
Activity Recognition Subscription question

### ISSUE THREAD

**Issue by mynavy** [mcharmas/Android-ReactiveLocation#48]
Hi , 

Im subscribing to activity recognition with this function in a service : 
```javascript
public void activity_subs(){
      
        activitySubscription=   locationProvider.getDetectedActivity(0) // detectionIntervalMillis

                .subscribe(new Action1<ActivityRecognitionResult>() {
                    @Override
                    public void call(ActivityRecognitionResult detectedActivity) {
                        //doSthImportantWithObtainedActivity(detectedActivity);
}
});
}
```
Now i've noticed that if i call this function multiple times and then i call to :  
```javascript
 activitySubscription.unsubscribe();
```
Then Activity Recognition still keeps running even though i want it to stop. 

so if im calling to activity_subs() multiple times it does not override but gets new subscription every call??

Thanks.

**Comment by mcharmas** [comment]
Hi,
this is how RxJava works in general. Every time you call subscribe new subscription object is created. As I understand you are holding the reference only to last one that's why when you unsubscribe it only unsubscribes the last one.

If you need multiple subscriptions you can aggregate them in the single one using rxjava ```CompositeSubscription``` object. If you need only one subscription you have to check by yourself if you are subscribed and subscribe only once.

**Comment by mynavy** [comment]
Thanks for the informative answer i'll try that. 

By the way , i've tested geofencing while driving in about 100 km/h and it looks like geofencing doesnt trigger at that speed at all . 

I guess it's something with the radius? i tryied it with 300m radius.
Maybe bigger radius would help ?

**Comment by mcharmas** [comment]
I think it really depends on device and in what state it is while passing geofence but
I am no expert in this area. Unfortunatelly only google is becouse GMS are closed-source.

I guess you have to experiment.
