### ISSUE TITLE
Strange Activity Recognition behaviour

### ISSUE THREAD

**Issue by mynavy** [mcharmas/Android-ReactiveLocation#50]
Hi.

I've subscribed activity recognition in two services. 

the first service listens to activity recognition with this call : 
```javascript
activitySubscription=   locationProvider.getDetectedActivity(0) // detectionIntervalMillis

                .subscribe(new Action1<ActivityRecognitionResult>() {
                               @Override
                               public void call(ActivityRecognitionResult detectedActivity) {
                                   //doSthImportantWithObtainedActivity(detectedActivity);
}
});
```

The second service listens to activity recognition with the same variable : activitySubscription

Now , when i call from the first service to
 ```javascript 
activitySubscription.unsubscribe();
 ```

The second subscription on the second service also unsubscribing for some reason. 

What can be the result of this issue?
Thanks

**Comment by mcharmas** [comment]
Hi,
yes, it may work like this. The problem is that under the hood there is one PendingIntent - the same one for both subscriptions. When you unsubscribe one the PendingIntent is removed from GMS and the other subscription stops receiving notifications. This probably can be fixed somehow but I would have to think about it.

In the meantime you can create maybe some ConnectableObservable in RxJava that has one subscription to GMS underneath and use it from both services.

**Comment by mynavy** [comment]
Thanks ! 

Maybe you can show some example of this ? 

And what about``` CompositeSubscription``` ? is it possible to use to solve the problem ?

**Comment by mcharmas** [comment]
```CompositeSubscription``` is used for aggregating multiple subscriptions into one so it will not be usefull here. What I ment is this: https://github.com/ReactiveX/RxJava/wiki/Connectable-Observable-Operators

**Comment by mynavy** [comment]
Thanks for the answer!
I will try to  implement with it, sounds interesting.
