### ISSUE TITLE
Mock locations not working

### ISSUE THREAD

**Issue by IgorGanapolsky** [mcharmas/Android-ReactiveLocation#64]
Hello,
I am testing your sample where I am setting a mock location.  However, it doesn't do anything.  My Google map still shows me at my old location.  Please advise.

Igor

**Comment by mcharmas** [comment]
I think you have to enable location mocking in device developer settings.

**Comment by IgorGanapolsky** [comment]
Already enabled.

**Comment by mcharmas** [comment]
I am not sure If I am able to help you. Try mocking location and checking it in main sample app screen.

**Comment by IgorGanapolsky** [comment]
You are saying that your mock location feature changes users's location in Google Maps.  You are able to confirm this?

**Comment by mcharmas** [comment]
Sorry, I needed to take a look at the code of sample.

Mocking location works for all apps that use GMS for location but only for the time of subscription.
When you quit mocking activity, subscriptions is finished and mocking stops.
That's why you see real location in google maps.

If you need to mock location for outside of your app you probably need to implement
some kind of service that holds subscription in background and provide some notficiation
that would finish mocking when invoked.

This feature works as expected so I am closing this issue.
