### ISSUE TITLE
sample PlacesActivity doesn't work for me

### ISSUE THREAD

**Issue by Rainer-Lang** [mcharmas/Android-ReactiveLocation#66]
I'm running the sample app -> Places.
But if I write something in "PLACE AUTOCOMPLETE" nothing happens...

**Comment by mcharmas** [comment]
Please read https://github.com/mcharmas/Android-ReactiveLocation#sample

**Comment by Rainer-Lang** [comment]
Thanks for the advice.
What I did yesterday: I activated Places API and also generated the API-Key for the sample. Copied API-Key in gradle.properties. Still nothing.

**Comment by mcharmas** [comment]
Sorry but I don't know how to help you. Take a look if you havn't made a mistake in API key or environment gradle property name. I have it set up in my main gradle properties (~/.gradle/gradle.properties). The property name is: ```REACTIVE_LOCATION_GMS_API_KEY```.

I've just checked and everything works for me so probably the issue is connected with api key.

**Comment by Rainer-Lang** [comment]
I have seen in my console that there are client response errors. But I have no error in the sample app.

**Comment by Rainer-Lang** [comment]
@mcharmas Now all is working. I think your lib is great for me. Thanks a lot for your hard work! :-)

**Comment by SudhakaraKS31** [comment]
for Places query iam not getting any suggestions text , other than that everything is working for me, may i know what is the issue
