### ISSUE TITLE
Is it wise to create a new instance of GoogleApiClient for every Observable?

### ISSUE THREAD

**Issue by andradf** [mcharmas/Android-ReactiveLocation#67]
Great library! It is certainly going to be useful. However, I have one concern. It seems that for every Observable that extends BaseObservable a new instance of GoogleApiClient is created. Is this not a waste of resources? Wouldn't it be better if ReactiveLocationProvider would somehow cache the apiClient?

**Comment by mcharmas** [comment]
Great you like it! I was thinking about it but actually you could use LocationProvider from multiple threads. To be hones I have no idea what is the support for that in GMS. I havn't seen anything about it in the docs and sources are closed. The safest option I had while implementing this was to use separate Google Api Clients. Do you have any metrics how wasteful is it in terms of memory?

I am not closing to the idea of making the library better but I am not sure if we have enough information how to do it.

Writing in the docs that library can be used only from one thread is not an option for me because observables by their definition should be thread agnostinc. Do you have any idea how to solve this?

**Comment by saiimons** [comment]
@andradf : Do you need to create a lot of different observables for the location, with different parameters ?
If no, you can use the [share operator](http://reactivex.io/RxJava/javadoc/rx/Observable.html#share()) to handle multiple subscriptions to your client without duplicating it.
Using a singleton or the application object, you could store your own observable, and share it.
(You can also go crazy and use [concatMap](http://reactivex.io/RxJava/javadoc/rx/Observable.html#concatMap(rx.functions.Func1)) to change the observable you share without having to unsubscribe)
*I was working on a similar library until I stumbled upon this one, and was using share wiithout facing any issue.*

@mcharmas I'll be glad to contribute :)

**Comment by mohamedkomalo** [comment]
@mcharmas, @saiimons  
Hi, any news about this issue ?

I think what is important to give the developer the ability to use his instance of GoogleApiClient, so there can be two options either to let the library create the client or the developer to create the client himself.

**Comment by mcharmas** [comment]
The point of this library is not to manage GoogleApiClient by yourself. I think it is the biggest problem it solves. To be honest I am not sure if multiple GoogleApiClient connection are really memory consuming - never measured it.

The only solution I can see is to deliver your own Observable<GoogleApiClient> on Provider creation and manage it's lifecycle by yourself. It's quite big of change in library and time is recently very restricted resource for me. If anyone prepares PR with such change I can review and merge it.

**Comment by mcharmas** [comment]
Still no idea how to solve it and I don't think is that resource intesive.
