### ISSUE TITLE
getLastKnownLocation() only from GPS

### ISSUE THREAD

**Issue by Shahroz16** [mcharmas/Android-ReactiveLocation#96]
First, Thank you for the great library. 
I have a question, I want to only getlastknownlocations from the GPS. 
I don't want to filter the value, I just want to get it from GPS source every time I want it.
is there anyway to do that? 
Looking forward to your response, thanks.

**Comment by Rainer-Lang** [comment]
@Shahroz16 Some really good libraries seem to be abandoned... :(

**Comment by mcharmas** [comment]
@Rainer-Lang sorry, had some vacations... Now slowly going back to work. I'll try to refer to all issues during the incoming week.

**Comment by Rainer-Lang** [comment]
@mcharmas Hi, welcome back :)
Fortunately you "only" had vacations ;-)
Your library is really great! One of my favorite.
Take your time.

**Comment by esafirm** [comment]
@Shahroz16 this SO link is pretty much answer your question
http://stackoverflow.com/questions/29331683/can-i-use-fusedlocationproviderapi-and-force-using-gps-only

This library is wrapping `FusedLocationProvider` which combine all the location provider in order to reduce power usage.

CMIIW even if you can `filter` the provider from `location.getProvider()` it will be useless since it will return **"fused"** value (which differ from `LocationManager` that actually return **GPS_PROVIDER** or **NETWORK_PROVIDER**) 

My solution for you is to make a `LocationManager` Rx Wrapper yourself.
